# notifications:
#   slack: notyet-hexa:pYcmfHQygnnf8vFtwrUGhnL9
language: cpp
compiler: g++
before_install:
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get -qq update
  - wget https://ftp.gnu.org/gnu/bison/bison-3.0.tar.gz -O /tmp/bison-3.0.tar.gz
  - tar -xzvf /tmp/bison-3.0.tar.gz
  - pushd bison-3.0 && ./configure --prefix=/usr && make && sudo make install && popd
install:
  - sudo apt-get install -y make flex # bison
  - sudo apt-get install -qq g++-6
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-6 90
  - sudo unlink /usr/bin/g++ && sudo ln -s /usr/bin/g++-6 /usr/bin/g++
script:
  - bison --version
  - flex --version
  - make --version
  - g++ --version
  - find tests -type f -name '*.test'
  - chmod a+x tests/run.sh
  - make
  - make test
  - 'curl -X POST -H Content-type: application/json --data @stack_result.json  https://hooks.slack.com/services/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'