# notifications:
#   slack: notyet-hexa:pYcmfHQygnnf8vFtwrUGhnL9
language: cpp
compiler: g++
before_install:
  - export COVERALLS_REPO_TOKEN=aooF1UtCWnk4I4qCYg9hEyhTF0CL9xVlV
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get -qq update
  - wget https://ftp.gnu.org/gnu/bison/bison-3.0.tar.gz -O /tmp/bison-3.0.tar.gz
  - tar -xzvf /tmp/bison-3.0.tar.gz
  - pushd bison-3.0 && ./configure --prefix=/usr && make && sudo make install && popd
  - pip install --user cpp-coveralls
install:
  - sudo apt-get install -y make flex # bison
  - sudo apt-get install -qq g++-6
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-6 90
  - sudo unlink /usr/bin/g++ && sudo ln -s /usr/bin/g++-6 /usr/bin/g++
script:
  - bison --version
  - flex --version
  - make --version
  - g++ --version
  - chmod a+x tests/run.sh
  - make mode=coverage
  - make mode=coverage test
  - gcov build/release/*
after_script:
  - chmod a+x slack.sh
  - ./slack.sh
after_success:
  - coveralls --include src --gcov-options '\-lp'